apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-system
  labels:
    app: grafana
    component: core
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 29997
  selector:
    app: grafana
    component: core
